const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ctx = vm.createContext({console});
vm.runInContext(fs.readFileSync(__dirname + '/Kode.gs', 'utf8'), ctx);
assert.equal(typeof ctx.nodeBReport_, 'function', 'NODE-B aggregator missing');
const rows = [['SITE ID','STATUS','PROGRAM'],['A','INSTALASI','New Infra'],['B','06.RFS','New Infra'],['C','7. Uji Terima','New Infra'],['D','01.HOLD','Other'],['E','00.PLAN DROP','Other'],['F','02.MATERIAL PREPARATION','Other'],['G','05.INSTALASI',' '],['H','on air','New Infra'],['I','5. Finish Install','New Infra'],['J','','Other'],['','6. On Air','']];
const d = ctx.nodeBReport_(rows);
assert.equal(d.order, 10);
assert.equal(d.deployment, 6);
assert.equal(d.onAir, 2);
assert.equal(d.gap, 8);
assert.equal(d.programs.length, 2);
const p = d.programs.find(p => p.name === 'New Infra');
assert.deepEqual(JSON.parse(JSON.stringify(p)), {name:'New Infra',order:5,closed:2,open:3,progress:40});
assert.equal(d.milestones.reduce((n,s)=>n+s.total,0),10);
assert.equal(d.milestones.find(s=>s.name==='Drop').total,2);
assert.equal(d.milestones.find(s=>s.name==='Matdel').total,1);
const material = ctx.nodeBReport_([rows[0],['A','MATERIAL PREPARATION','X'],['B','material delivery','X'],['C','02.MATERIAL PREPARATION','X'],['D','04.MATERIAL DELIVERY','X']]);
assert.equal(material.milestones.find(s=>s.name==='Matdel').total,4);
assert.equal(ctx.nodeBReport_([rows[0]]).gap,0);
assert.throws(()=>ctx.nodeBReport_([['STATUS']]), /SITE ID/);
assert.equal(typeof ctx.nodeBCurve_, 'function', 'S-curve aggregator missing');
const curve = ctx.nodeBCurve_([['SITE ID','KOMITMEN OA','REALISASI OA'],['A','1/2/2026','2026-02-02'],['B','01/02/2026','2/2/2026'],['C','03/02/2026','31/02/2026'],['D','',''],['','1/2/2026','2/2/2026']]);
assert.deepEqual(JSON.parse(JSON.stringify(curve.points)),[{date:'2026-02-01',plan:2,actual:0,planDaily:2,actualDaily:0},{date:'2026-02-02',plan:2,actual:2,planDaily:0,actualDaily:2},{date:'2026-02-03',plan:3,actual:2,planDaily:1,actualDaily:0}]);
assert.equal(curve.invalidActual,1);
assert.equal(ctx.nodeBCurve_([['SITE ID','KOMITMEN OA','REALISASI OA']]).points.length,0);
assert.throws(()=>ctx.nodeBCurve_([['SITE ID']]), /KOMITMEN OA/);
const html = fs.readFileSync(__dirname + '/Index.html', 'utf8');
for (const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)) new vm.Script(m[1]);
assert.match(html, /function loadNodeBReport\(/, 'NODE-B loader missing');
assert.match(html, /name === 'nodeb'/, 'NODE-B tab must load data');
const host = {};
ctx.document = {getElementById:()=>host};
vm.runInContext(html.slice(html.indexOf('function renderNodeBCurve('),html.indexOf('function renderNodeB(data)')),ctx);
ctx.renderNodeBCurve(curve);
assert.ok(host.innerHTML.includes('<svg'));
assert.ok(host.innerHTML.includes('Komitmen OA: 3'));
assert.ok(!host.innerHTML.includes('NaN'));
ctx.renderNodeBCurve({points:[]});
assert.equal(host.textContent,'Tidak ada tanggal OA valid.');
console.log('NODE-B aggregation, S-curve rendering and frontend syntax checks passed');
