const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ctx = vm.createContext({console});
vm.runInContext(fs.readFileSync(__dirname + '/Kode.gs', 'utf8'), ctx);
assert.equal(typeof ctx.nodeBReport_, 'function', 'NODE-B aggregator missing');
const rows = [['SITE ID','STATUS','PROGRAM'],['A','INSTALASI','New Infra'],['B','06.RFS','New Infra'],['C','7. Uji Terima','New Infra'],['D','01.HOLD','Other'],['E','00.PLAN DROP','Other'],['F','02.MATERIAL PREPARATION','Other'],['G','05.INSTALASI',' '],['H','on air','New Infra'],['I','5. Finish Install','New Infra'],['J','','Other'],['','6. On Air','']];
const d = ctx.nodeBReport_(rows);
assert.equal(d.order, 10);
assert.equal(d.deployment, 6);
assert.equal(d.onAir, 2);
assert.equal(d.gap, 8);
assert.equal(d.programs.length, 2);
const p = d.programs.find(p => p.name === 'New Infra');
assert.deepEqual(JSON.parse(JSON.stringify(p)), {name:'New Infra',order:5,closed:2,open:3,progress:40});
assert.equal(d.milestones.reduce((n,s)=>n+s.total,0),10);
assert.equal(d.milestones.find(s=>s.name==='Drop').total,2);
assert.equal(d.milestones.find(s=>s.name==='Matdel').total,1);
assert.equal(ctx.nodeBReport_([rows[0]]).gap,0);
assert.throws(()=>ctx.nodeBReport_([['STATUS']]), /SITE ID/);
const html = fs.readFileSync(__dirname + '/Index.html', 'utf8');
for (const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)) new vm.Script(m[1]);
assert.match(html, /function loadNodeBReport\(/, 'NODE-B loader missing');
assert.match(html, /name === 'nodeb'/, 'NODE-B tab must load data');
console.log('NODE-B aggregation and frontend syntax checks passed');
